query HostQuery {
    NetworkDevice {
        edges {
            node {
                id
                hostname {value}
                site {value}
                role {value}
            }
        }
    }
}